### ISSUE TITLE
testing result for VAE

### ISSUE THREAD

**Issue by MTK10152** [2019-dl-training-program/Lab4#12]
Firstly, I use traditional AE to test reconstruction like that input is "click" and output is "click".
And then I use VAE to test  reconstruction without KL loss and I got output "clickik" even the reconstruction loss is 0.0000001. Why the tail of characters is wrong when reconstruction loss is quite small. Why test result is different between AE and VAE without KL loss?

**Comment by robert80203** [comment]
Although VAE without KL loss can be very similar to AE, their backbone concepts are still different. When you train AE, the input will be compressed by the encoder and directly decompressed by the decoder; that is, AE is deterministic model. However, VAE is not a deterministic model since you will draw samples from N(0,I) and do affine transformation with mu and var from the encoder. As a result, the testing results of AE and VAE may be different. Ideally, if you draw samples for many times, the results should be quite similar.
